version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend
    extra_hosts:
      - ocm.app:192.168.222.254
    environment:
      - VIRTUAL_HOST=ocm.app
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./hosts/app.conf:/etc/apache2/sites-enabled/ocm.app.conf:ro
    networks:
      app-network:
